accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),

    path('activate/<uidb64>/<token>/', views.activate, name='activate'), 
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'), 
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('3rdparty/login/cancelled/', views.returntolog, name='returntolog'),

    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('address/', views.address, name='address'),
    path('change_password/', views.change_password, name='change_password'),
    path('ac_details/', views.ac_details, name='ac_details'),
    path('edit_address/<int:id>/', views.edit_address, name='edit_address'),
    path('delete-address-profile/<int:id>/', views.delete_address_profile, name='delete_address_profile'),
    path('wallet/', views.wallet, name='wallet'),

    path('order_detail_view_user/<int:order_id>/', views.order_detail_view_user, name='order_detail_view_user'),
    path('download_pdf/<int:order_id>/', views.generate_pdf, name='download_pdf'),

    path('apply_referral_code/', views.apply_referral_code, name='apply_referral_code'),
]

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('increment-cart-item/<int:product_id>/', views.increment_cart_item, name='increment_cart_item'),
    path('decrement-cart-item/<int:product_id>/', views.decrement_cart_item, name='decrement_cart_item'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout')
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
    path('accounts/', include('allauth.urls')),

    path('django-admin/', include('admin_panel.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from store.models import Product
from accounts.models import Account
import random
from decimal import Decimal
from django.utils import timezone
from django.conf import settings

class Order(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Confirmed', 'Confirmed'),
        ('Processing', 'Processing'),
        ('Shipped', 'Shipped'), 
        ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
        ('Return Request', 'Return Request'), 
        ('Return Pending', 'Return Pending'),
        ('Return Cancelled', 'Return Cancelled'),
        ('Return Success', 'Return Success'),
        ('Payment Pending', 'Payment Pending')
    ]
    address_line1 = models.CharField(max_length=255, null=True)
    address_line2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    pincode = models.CharField(max_length=20, null=True)
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255, null=True, blank=True)  # New field for name
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Total price
    tax = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True)
    shipping_fee = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=50)  
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending', null=True)
    payment_method = models.CharField(max_length=50, null=True)
    email = models.EmailField(null=True)  # Store user's email
    created_at = models.DateTimeField(auto_now_add=True, null=True)  # Date and time of order creation
    updated_at = models.DateTimeField(auto_now=True, null=True)
    order_number = models.CharField(max_length=6, unique=True, null=True, blank=True)  # New field for order number
    is_ordered = models.BooleanField(default=False)
    coupon_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    coupon_id = models.IntegerField(null=True, blank=True)  # New field for coupon ID applied
    
    def __str__(self):
        return f"Order #{self.order_number} - {self.user.username if self.user else 'Anonymous'}"

    def get_status_choices(self):
        return self.STATUS_CHOICES

    def generate_unique_order_number(self):
        """Generate a unique 6-digit order number."""
        while True:
            order_number = str(random.randint(100000, 999999))
            if not Order.objects.filter(order_number=order_number).exists():
                return order_number


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(null=True)
    sub_total = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    def __str__(self):
        return f"{self.quantity} x {self.product.product_name}"
from django.db import models

class Payment(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE, related_name='payment', null=True)
    payment_method = models.CharField(max_length=50, null=True)
    payment_status = models.CharField(max_length=20, default='Pending', null=True)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    
    # New fields for Razorpay integration
    razorpay_payment_id = models.CharField(max_length=100, null=True, blank=True)
    razorpay_order_id = models.CharField(max_length=100, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"Payment for Order #{self.order.id}"

    def save(self, *args, **kwargs):
        # Optionally add custom save logic here
        super(Payment, self).save(*args, **kwargs)


class Coupon(models.Model):
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('expired', 'Expired'),
    )

    ACTION_CHOICES = (
        ('block', 'Block'),
        ('unblock', 'Unblock'),
    )

    code = models.CharField(max_length=20, unique=True, verbose_name="Coupon Code")
    description = models.TextField(null=True, blank=True, verbose_name="Description")
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Discount Percentage")
    minimum_purchase_amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Minimum Purchase Amount")
    max_redeemable_value = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Max Redeemable Value", null=True)  # New field
    quantity = models.PositiveIntegerField(verbose_name="Quantity", null=True)
    expiry_date = models.DateField(verbose_name="Expiry Date")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Status")
    action = models.CharField(max_length=10, choices=ACTION_CHOICES, default='block', verbose_name="Action")

    def __str__(self):
        return self.code


class Wallet(models.Model):
    PAYMENT_TYPE_CHOICES = [
        ('credit', 'Credit'),
        ('debit', 'Debit'),
        ('transfer', 'Transfer'),
        ('cash', 'Cash'),
    ]
    user = models.OneToOneField(Account, on_delete=models.CASCADE, related_name='wallet')
    wallet_balance = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))

    def __str__(self):
        return f"{self.user.username}'s Wallet"

    def update_balance(self, transaction_type, amount):
        amount = Decimal(str(amount))   # Ensure amount is a Decimal
        if transaction_type == 'credit':
            self.wallet_balance += amount
        elif transaction_type == 'debit':
            self.wallet_balance -= amount
        self.save()

class WalletTransaction(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, related_name='transactions')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_type = models.CharField(max_length=10, choices=Wallet.PAYMENT_TYPE_CHOICES)
    description = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.wallet.user.username}'s {self.transaction_type} - {self.amount}"


class ReferralOffer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='referral_offers', null=True, blank=True)
    code = models.CharField(max_length=50, unique=True, help_text="Unique code for the referral offer.")
    description = models.TextField(help_text="Description of the referral offer.", null=True)
    reward_amount = models.DecimalField(max_digits=10, decimal_places=2, help_text="Amount of reward for the referral.")
    is_active = models.BooleanField(default=True, help_text="Indicates if the offer is currently active.")
    start_date = models.DateTimeField(default=timezone.now, help_text="Start date of the offer.", null=True)
    end_date = models.DateTimeField(null=True, blank=True, help_text="End date of the offer.")
    usage_limit = models.PositiveIntegerField(null=True, blank=True, help_text="Maximum number of times the offer can be used.")
    created_at = models.DateTimeField(auto_now_add=True, help_text="When the offer was created.")
    updated_at = models.DateTimeField(auto_now=True, help_text="When the offer was last updated.")

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = "Referral Offer"
        verbose_name_plural = "Referral Offers"
        ordering = ['-start_date']



class OrderedItems(models.Model):
    order_number = models.CharField(max_length=6, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    size = models.CharField(max_length=50)
    shipping_fee = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=50) 

    def save(self, *args, **kwargs):
        self.total = self.unit_price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.order_number}, {self.product}, {self.unit_price}, {self.quantity}, {self.size}"

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
# Create your models here.

class Product(models.Model):
    product_name    = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(max_length=200, unique=True)
    description     = models.TextField(max_length=1000, blank=True)
    price           = models.IntegerField(null=True)
    images          = models.ImageField(upload_to='photos/products', null=True)
    image1 = models.ImageField(upload_to='photos/products', blank=True, null=True)
    image2 = models.ImageField(upload_to='photos/products', blank=True, null=True)
    stock_small = models.IntegerField(default=0)
    stock_medium = models.IntegerField(default=0)
    stock_large = models.IntegerField(default=0)
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date    = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)
    # size            = models.IntegerField(null=True)
    wishlisted      = models.BooleanField(default=False)
    wishlist_count  = models.PositiveIntegerField(default=0)
    wishlist_added_date = models.DateTimeField(null=True, blank=True)
    old_price       = models.IntegerField(null=True, blank=True)
    discount_percentage = models.PositiveIntegerField(default=0)
    product_disc_added = models.BooleanField(default=False, null=True)
    cat_disc_added = models.BooleanField(default=False, null=True)
    applied_offer_name = models.CharField(max_length=20 ,null=True)
    applied_offer_percentage = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
   
    
    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name
    
    def get_total_stock(self):
        return self.stock_small + self.stock_medium + self.stock_large

        # Model-level validation to ensure stock doesn't go below 0
    def clean(self):
        if self.stock_small < 0:
            raise ValidationError('Stock for small size cannot be less than 0.')
        if self.stock_medium < 0:
            raise ValidationError('Stock for medium size cannot be less than 0.')
        if self.stock_large < 0:
            raise ValidationError('Stock for large size cannot be less than 0.')

    def save(self, *args, **kwargs):
    # Ensure price is calculated correctly based on old_price and discount_percentage
        if self.old_price is not None:
            if self.discount_percentage and self.discount_percentage > 0:
                discount_amount = (self.old_price * self.discount_percentage) / 100
                self.price = self.old_price - discount_amount
            else:
                self.price = self.old_price  # No discount applied
            
        self.clean()
        super(Product, self).save(*args, **kwargs)


    # def save(self, *args, **kwargs):
    #     # Calculate the price based on old_price and discount_percentage
    #     if self.old_price and self.discount_percentage:
    #         discount_amount = (self.old_price * self.discount_percentage) / 100
    #         self.price = self.old_price - discount_amount
    #     super(Product, self).save(*args, **kwargs)

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery' 


from django.utils import timezone
from store.models import Product  # Import the Product model
from category.models import Category  # Import the Category model

class Offer(models.Model):
    OFFER_TYPE_CHOICES = [
        ('product', 'Product'),
        ('category', 'Category'),
    ]

    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]

    OFFER_ACTION_CHOICES = [
        ('block', 'Block'),
        ('unblock', 'Unblock'),
    ]

    offer_name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    offer_type = models.CharField(max_length=50, choices=OFFER_TYPE_CHOICES)
    offer_percentage = models.DecimalField(max_digits=5, decimal_places=2)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='active')
    action = models.CharField(max_length=50, choices=OFFER_ACTION_CHOICES, default='unblock')
    products = models.ManyToManyField(Product, blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def clean(self):
        if Offer.objects.filter(offer_name=self.offer_name).exists():
            raise ValidationError(f"Offer with the name '{self.offer_name}' already exists.")

    def save(self, *args, **kwargs):
        self.full_clean()  # Call clean method to validate before saving
        super().save(*args, **kwargs)

templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{ user.first_name }},

Thank you for registering on our site. To complete your registration, please use the OTP code below:

Your OTP code is: {{ otp }}

Please enter this code on the verification page to activate your account. If you did not register for an account, please ignore this email.

Best regards,
The Team

{% endautoescape %}

templates/accounts/my_orders.html
{% extends 'base.html' %}

{% block content %}

<section class="section-content padding-y bg">

{% include 'includes/alerts.html' %}

    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}
        <main class="col-md-9">
            <article class="card" style="width: 1000px;">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Your Order History</strong>
            </header>
            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-12">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">Order ID</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Total Price</th>
                                    <th scope="col">Payment method</th>
                                    <th scope="col">Status</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <th scope="row">{{ order.order_number }}</th>
                                    <td>{{ order.created_at }}</td>
                                    <td>₹{{ order.grand_total }}</td>
                                    <td>
                                        {% if order.payment_method == "cash_on_delivery" %}
                                            Cash on Delivery
                                        {% elif order.payment_method == "wallet" %}
                                            Wallet
                                        {% else %}
                                            {{ order.payment_method }}
                                        {% endif %}
                                    </td>
                                    
                                    <td class="{% if order.status == 'Return Pending' or order.status == 'Pending' %}status-pending{% elif order.status == 'Return Cancelled' or order.status == 'Payment Pending' %}status-return-cancelled{% elif order.status == 'Return Success' %}status-return-success{% elif order.status == 'Cancelled' %}status-cancelled{% endif %}">
                                        {% if order.status == 'Delivered' %}
                                        <span class="text-success">{{ order.get_status_display }}</span>
                                        {% elif order.status == 'Return Request' %}
                                        <span class="text-danger">Return Request Sended</span>
                                        {% elif order.status == 'Return Pending' or order.status == 'Pending' %}
                                        {{ order.get_status_display }}
                                        {% elif order.status == 'Return Cancelled' %}
                                        {{ order.get_status_display }}
                                        {% elif order.status == 'Return Success' %}
                                        {{ order.get_status_display }}
                                        {% elif order.status == 'Cancelled' %}
                                        {{ order.get_status_display }}
                                        {% else %}
                                        {{ order.get_status_display }}
                                        {% endif %}
                                    </td>
                                    <td class="text-center vertical-center">
                                        {% if order.status == 'Pending' or order.status == 'Confirmed' or order.status == 'Processing' %}
                                        <form method="post" action="{% url 'my_orders' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="order_id" value="{{ order.id }}">
                                            <button type="submit" class="btn btn-danger" style="font-weight: bold;">Cancel</button>
                                        </form>
                                        {% elif order.status == 'Delivered' %}
                                        <form method="post" action="{% url 'my_orders' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="order_id" value="{{ order.id }}">
                                            <button type="submit" class="btn btn-danger" style="font-weight: bold;">Return</button>
                                        </form>
                                        {% elif order.status == 'Payment Pending' %}
                                        <form method="post" action="{% url 'retry_page' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="order_id" value="{{ order.id }}">
                                            <button type="submit" class="btn btn-success" style="font-weight: bold;">Pay Now</button>
                                        </form>
                                        {% elif order.status == 'Cancelled' %}
                                        <button type="button" class="btn btn-secondary" disabled style="font-weight: bold;">Cancelled</button>
                                        {% endif %}
                                        <td>
                                            <form action="{% url 'order_detail_view_user' order.id %}" method="get">
                                                <button type="submit" class="btn btn-primary" style="font-weight: bold;">Details</button>
                                            </form>
                                        </td>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="5">No orders found.</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>

</section>
<style>
.text-success {
    color: green; /* Change this to your desired shade of green */
}

.text-center.vertical-center {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
}

.table {
    width: 100%;
}

.table td, .table th {
    vertical-align: middle;
}
.text-success {
    color: green; /* Change this to your desired shade of green */
}
.status-pending {
    color: rgb(255, 132, 0);
}
.status-return-cancelled {
    color: red;
}
.status-return-success {
    color: rgb(0, 255, 60);
}
.status-cancelled {
    color: red;
}
</style>
{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{ user.first_name }},

As requested, please click link to reset your password.
http://{{ domain }}{% url 'resetpassword_validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email. 

{% endautoescape %}

templates/accounts/wallet.html
{% extends 'base.html' %}

{% block content %}
<section class="section-content padding-y bg">
    {% include 'includes/alerts.html' %}
    
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <!-- Wallet Balance Section -->
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h4 class="card-title">Wallet</h4>
                        <div class="wallet-balance mb-4">
                            <h2 class="display-4">₹{{ wallet.wallet_balance }}</h2>
                            <p>Wallet Balance</p>
                        </div>
                         <!-- Refer and Earn Button -->
                         <div class="text-right mb-3">
                            <a href="#" class="btn btn-success" style="background-color: #008211;" data-bs-toggle="modal" data-bs-target="#referModal">Refer and Earn</a>
                        </div>
                        

                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Type of Payment</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for transaction in wallet_transactions %}
                                <tr>
                                    <td>{{ transaction.date }}</td>
                                    <td>{{ transaction.get_transaction_type_display }}</td>
                                    <td class="{% if transaction.transaction_type == 'credit' %}text-success{% else %}text-danger{% endif %}">
                                        {% if transaction.transaction_type == 'credit' %}+{% else %}-{% endif %}₹{{ transaction.amount }}
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="3">No transactions found.</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>
        </div> <!-- row.// -->
    </div>
    <!-- Modal -->
<div class="modal fade" id="referModal" tabindex="-1" aria-labelledby="referModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="referModalLabel">Refer and Earn</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
            </div>
            <div class="modal-body">
                <h5>Your Code: {{ referral_code }}</h5>
                <br>
                <form id="referForm">
                    <div class="mb-3">
                        <label for="friendCode" class="form-label">Enter Your Friend's Code</label>
                        <input type="text" class="form-control" id="friendCode" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

</section>

<style>
    .wallet-balance {
        text-align: center;
    }
    
    .wallet-balance .display-4 {
        color: #008000;
        font-weight: bold;
    }
    
    .wallet-balance p {
        font-size: 18px;
        margin-top: -10px;
        color: #666;
    }
    
    .table th, .table td {
        vertical-align: middle;
    }
    
    .table-bordered td {
        text-align: center;
    }
</style>
<script>
    document.getElementById('referForm').addEventListener('submit', function(event) {
        event.preventDefault();
        const friendCode = document.getElementById('friendCode').value;
        // Handle the form submission, e.g., send the code to the server or show a confirmation
        console.log('Friend Code:', friendCode);
        // Close the modal
        const modalElement = document.getElementById('referModal');
        const modal = bootstrap.Modal.getInstance(modalElement);
        modal.hide();
    });
</script>
<!-- Add this script in your template -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('#referForm').on('submit', function(event) {
            event.preventDefault();
            var friendCode = $('#friendCode').val();
            
            $.ajax({
                url: '{% url "apply_referral_code" %}',  // URL for the view handling referral codes
                type: 'POST',
                data: {
                    'friend_code': friendCode,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    if (response.success) {
                        alert(response.message);
                        $('#referModal').modal('hide');
                    } else {
                        alert(response.message);
                    }
                }
            });
        });
    });
</script>

{% endblock %}